"""empty message

Revision ID: 794242d2896d
Revises: a76e470e73ab
Create Date: 2024-12-22 23:38:05.379809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794242d2896d'
down_revision = 'a76e470e73ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('sum_of_bets', sa.Integer(), nullable=True),
    sa.Column('bonuses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('facebook_pic', sa.String(length=128), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('color_scheme', sa.String(length=30), nullable=True),
    sa.Column('deck_type', sa.String(length=20), nullable=True),
    sa.Column('social_id', sa.String(length=64), nullable=True),
    sa.Column('preferred_language', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('player',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_position'), ['position'], unique=False)

    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('closed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_room_name'), ['room_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_user_id'), ['user_id'], unique=False)

    op.create_table('connections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('ready', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('autodeal', sa.Integer(), nullable=True),
    sa.Column('one_card_hands', sa.Integer(), nullable=True),
    sa.Column('rating_game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_winner_id'), ['winner_id'], unique=False)

    op.create_table('hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('trump', sa.String(length=1), nullable=True),
    sa.Column('cards_per_player', sa.Integer(), nullable=True),
    sa.Column('starting_player', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['starting_player'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'game_id', 'serial_no')
    )
    with op.batch_alter_table('hand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hand_game_id'), ['game_id'], unique=False)

    op.create_table('players',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('dealt_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.String(length=1), nullable=False),
    sa.Column('card_suit', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hand.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=True),
    sa.Column('bet_size', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hand.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=True),
    sa.Column('took_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hand.id'], ),
    sa.ForeignKeyConstraint(['took_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=1), nullable=False),
    sa.Column('card_suit', sa.String(length=1), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hand.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn_card')
    op.drop_table('turn')
    op.drop_table('hand_score')
    op.drop_table('dealt_cards')
    op.drop_table('players')
    with op.batch_alter_table('hand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hand_game_id'))

    op.drop_table('hand')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_winner_id'))
        batch_op.drop_index(batch_op.f('ix_game_room_id'))

    op.drop_table('game')
    op.drop_table('connections')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_room_name'))

    op.drop_table('room')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_position'))
        batch_op.drop_index(batch_op.f('ix_player_game_id'))

    op.drop_table('player')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('stats')
    # ### end Alembic commands ###
